$(document).ready(function(){
    $("#phone1").hide();
    $("#email1").hide();
    $("#phone2").hide();
    $("#email2").hide();
    $("#phone3").hide();
    $("#email3").hide();
    $("#phone4").hide();
    $("#email4").hide();
    $("#phone5").hide();
    $("#email5").hide();
    $("#phone6").hide();
    $("#email6").hide();

    $("#iphone1").click(function(){
        $("#phone1").toggle();
    });
    $("#iphone2").click(function(){
        $("#phone2").toggle();
    });
    $("#iphone3").click(function(){
        $("#phone3").toggle();
    });
    $("#iphone4").click(function(){
        $("#phone4").toggle();
    });
    $("#iphone5").click(function(){
        $("#phone5").toggle();
    });
    $("#iphone6").click(function(){
        $("#phone6").toggle();
    });

    $("#iemail1").click(function(){
        $("#email1").toggle();
    });
    $("#iemail2").click(function(){
        $("#email2").toggle();
    });
    $("#iemail3").click(function(){
        $("#email3").toggle();
    });
    $("#iemail4").click(function(){
        $("#email4").toggle();
    });
    $("#iemail5").click(function(){
        $("#email5").toggle();
    });
    $("#iemail6").click(function(){
        $("#email6").toggle();
    });
});